[tools]
"aqua:ViRb3/wgcf" = "latest"
"aqua:noborus/ov" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
chezmoi = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
herdr = "latest"
node = "26"
npm = "latest"
pnpm = "latest"
staticcheck = "latest"
tinymist = "latest"
usage = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "npm", "pnpm", "yarn"]
npm.package_manager = "bun"
