[tools]
age = "latest"
"aqua:ViRb3/wgcf" = "latest"
"aqua:noborus/ov" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
"aqua:vercel-labs/agent-browser" = "latest"
biome = "latest"
chezmoi = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
gotestsum = "latest"
herdr = "latest"
node = "26"
npm = "latest"
"npm:bash-language-server" = "latest"
"npm:nx" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yaml-language-server" = "latest"
pnpm = "latest"
staticcheck = "latest"
tinymist = "latest"
tombi = "latest"
usage = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "npm", "pnpm", "yarn"]
