[include]
# paths = ["/etc/topgrade.toml"]

[misc]

disable = ["config_update", "containers", "firmware", "flatpak", "node", "pip3", "pnpm", "self_update", "shell", "system", "typst", "vim", "waydroid", "yarn"]

[skills]
package_manager = "pnpm"
